---
title: "Machine Learning Pipelines for R with sl3"
date: "04/18/2018"
output:
  xaringan::moon_reader:
    lib_dir: libs
    chakra: libs/remark-latest.min.js
    css: ["default", "custom.css"]
    nature:
      highlightStyle: zenburn
      highlightLines: true
      navigation: {
        scroll: false
      }
---

```{r knitr_setup, echo=FALSE, message=FALSE}
knitr::opts_chunk$set(fig.width = 7, fig.height = 4.5, dpi = 300,
                      fig.cap = "", fig.align = "center")
showtext::showtext.opts(dpi = 300)
library(sl3)
library(methods)
```

class: center, middle

# `tlverse`: The Targeted Learning Analytics Ecosystem

---

# The `tlverse` Ecosystem I

What is the `tlverse`?

By analogy to [`tidyverse`](https://www.tidyverse.org/):

> The tidyverse is an opinionated collection of R packages designed for data science. All packages share an underlying design philosophy, grammar, and data structures. 

So, `tlverse` is:

* an opinioned collection of R packages for Targeted Learning
* sharing an underlying philosophy, grammar, and data structures

---

# The `tlverse` Ecosystem II

These are the main packages that represent the **core** of `tlverse`:

--

* [`sl3`](https://github.com/jeremyrcoyle/sl3)
  * _What?_ A modern object-oriented re-implementation of the Super Learner
    algorithm, employing recently developed paradigms for `R` programming.
  * _Why?_ A design that leverages modern tools for fast computation, is
    forward-looking, and can form one of the cornerstones of the `tlverse`.

--

* [`tmle3`](https://github.com/jeremyrcoyle/tmle3)
  * _What?_ A generalized framework that simplifies Targeted Learning by
    identifying and implementing a series of common regression procedures.
  * _Why?_ A common interface and engine that accommodates current algorithmic
    approaches to Targeted Learning and is still flexible enough to remain the
    engine even as new techniques are developed.

---

# The `tlverse` Ecosystem III

In addition to the engines that drive development in the `tlverse`, there are
some supporting packages -- in particular, we have two...

--

* [`origami`](https://github.com/jeremyrcoyle/origami)
  * _What?_ A generalized framework for flexible cross-validation
  * _Why?_ Cross-validation is a key part of ensuring error estimates are honest
    and preventing overfitting. It is an essential part of the both the Super
    Learner algorithm and Targeted Learning.

--

* [`delayed`](https://github.com/jeremyrcoyle/delayed)
  * _What?_ A framework for delayed computations (futures) based on task
    dependencies.
  * _Why?_ Efficient allocation of compute resources is essential when deploying
    large-scale, computationally intensive algorithms.

---

# `sl3`: Ensemble Learning Pipelines

* A _new_ framework and engine for optimal ensemble machine learning (Super
  Learning, stacked regression) that leverages recent developments in the `R`
  language (e.g., the `R6` OOP framework).

--

* Borrows (steals) good ideas from successful ML frameworks like `scikit-learn`.

--

* _Goal:_ Develop a self-contained ensemble learning engine that is not only
  faster than previous implementations but flexible enough to be used as the
  central building block for an ecosystem of Targeted Learning packages.

---

# Interlude: Object Oriented Programming in `Python` and `R` 

* OO concepts (classes with inherentence) were baked into Python from the first published version (version 0.9 in 1991)

--

* In contrast, `R` gets its OO "approach" from its predecessor, `S`, first released in 1976. For the first 15 years, S had no support for classes, then S got two OO frameworks bolted on in rapid succession: informal classes with S3 in 1991, and formal classes with S4 in 1998.

--

* This process continues, with new OO frameworks being periodically released, to try to improve the lackluster OO support in R, with reference classes (R5, 2010) and R6 (2014).

--

* Of these, R6 behaves most like Python classes (and also most like OOP focused languages like C++ and Java), including having method definitions be part of class definitions, and allowing objects to be modified by reference.

---
class: center, middle

# Juypter Demo

---

